id: A8A4FAF6D
title: 'The Sweet Sound of Perfect Joy: In Praise of the Goddess Sarasvatī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:42:11.584068
  last_modified_at: 2022-03-01 05:42:11.584073
