id: A8A4FAF6D
title: 'Ripples on the Ganges: In Praise of the Goddess Sarasvatī'
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:42:11.581556
  last_modified_at: 2022-03-01 05:42:11.581564
